print("DEFAULT CLIENT SCRIPT")
print("====================")
print()
print("You're seeing this message because no custom client script was configured.")
print()
print("To use your own client script, provide a path to your script when calling")
print("serve_tty(), for example:")
print()
print("serve_tty(client_script='/path/to/your/script.py')")
print()
print("Your client script should contain the logic you want to run in the")
print("terminal session.")